import { Coordinate } from './coordinate';
import { PriceRangeImpl } from './price-range-impl';
export declare function fromPercent(value: number, baseValue: number): number;
export declare function toPercent(value: number, baseValue: number): Coordinate;
export declare function toPercentRange(priceRange: PriceRangeImpl, baseValue: number): PriceRangeImpl;
export declare function fromIndexedTo100(value: number, baseValue: number): number;
export declare function toIndexedTo100(value: number, baseValue: number): Coordinate;
export declare function toIndexedTo100Range(priceRange: PriceRangeImpl, baseValue: number): PriceRangeImpl;
export declare function toLog(price: number): Coordinate;
export declare function fromLog(logical: number): number;
export declare function convertPriceRangeToLog(priceRange: PriceRangeImpl | null): PriceRangeImpl | null;
export declare function canConvertPriceRangeFromLog(priceRange: PriceRangeImpl | null): boolean;
export declare function convertPriceRangeFromLog(priceRange: PriceRangeImpl | null): PriceRangeImpl | null;
